using BankSwitch.Domain;

namespace BankSwitch.Application;

public interface IClock
{
    DateTimeOffset UtcNow { get; }
}

public sealed class SystemClock : IClock
{
    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
}

public interface ISecretProvider
{
    Task<string> GetSecretAsync(string name, CancellationToken cancellationToken = default);
}

public interface ISensitiveDataProtector
{
    string Protect(string plaintext, string purpose);
    string Unprotect(string protectedValue, string purpose);
}

public interface IHsmClient
{
    Task<MacValidationResult> ValidateMacAsync(IsoMessage message, SourceNode sourceNode, CancellationToken cancellationToken = default);
    Task<string> GenerateMacAsync(IsoMessage message, SinkNode sinkNode, CancellationToken cancellationToken = default);
    Task<string> GenerateMacForSourceAsync(IsoMessage message, SourceNode sourceNode, CancellationToken cancellationToken = default);

    /// <summary>
    /// Derives a terminal working/session key for the given key-serial-number under the
    /// terminal's base derivation key (identified by <paramref name="keyProfile"/>) and returns
    /// only the resulting key-check-value (KCV). The derived key itself never leaves the HSM.
    /// </summary>
    Task<string> DeriveTerminalKeyCheckValueAsync(string keyProfile, string keySerialNumber, CancellationToken cancellationToken = default);

    /// <summary>
    /// Translates an ISO 9564-1 PIN block from the terminal's zone key into the issuer's zone key
    /// inside the HSM. The clear PIN never exists outside the HSM boundary.
    /// Returns the re-encrypted PIN block under the destination key profile.
    /// </summary>
    Task<string> TranslatePinBlockAsync(string encryptedPinBlock, string sourceKeyProfile, string destinationKeyProfile, CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies an ISO 9564-1 PIN block against the cardholder's stored PIN reference data,
    /// entirely within the HSM boundary. Returns true when the PIN is correct.
    /// </summary>
    Task<bool> VerifyPinAsync(string encryptedPinBlock, string panSequenceNumber, string keyProfile, CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates a Card Verification Value (CVV/CVV2/iCVV) for a newly issued card.
    /// The CVV is computed inside the HSM using the Card Verification Key (CVK) and returned
    /// as a 3-digit string. The plaintext CVV must never be logged or persisted in clear text.
    /// </summary>
    Task<string> GenerateCvvAsync(string pan, int expiryMonth, int expiryYear, string serviceCode, string keyProfile, CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies a cardholder-supplied CVV value against the card's parameters using the CVK
    /// inside the HSM. Returns true when the CVV is correct.
    /// </summary>
    Task<bool> VerifyCvvAsync(string pan, int expiryMonth, int expiryYear, string serviceCode, string cvv, string keyProfile, CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies an EMV ARQC (Application Request Cryptogram) generated by an EMV chip card,
    /// and generates the ARPC (Application Response Cryptogram) that must be returned in the
    /// authorization response to the terminal. Returns null on verification failure.
    /// </summary>
    Task<EmvCryptogramResult?> VerifyArqcAndGenerateArpcAsync(string pan, string panSequenceNumber, string arqc, string transactionData, string arpcResponseCode, string keyProfile, CancellationToken cancellationToken = default);
}

/// <summary>Result of EMV ARQC verification: the ARPC for the terminal response and a flag indicating whether the chip data is authentic.</summary>
public sealed record EmvCryptogramResult(bool IsValid, string Arpc, string Script = "");

public sealed record MacValidationResult(bool IsValid, string Status, string? Reason = null)
{
    public static MacValidationResult NotApplicable { get; } = new(true, "NOT_APPLICABLE");
    public static MacValidationResult Passed { get; } = new(true, "PASSED");
    public static MacValidationResult Failed(string reason) => new(false, "FAILED", reason);
}

public interface ITransactionRepository
{
    Task<bool> ExistsDuplicateAsync(string sourceNodeId, string stan, string rrn, decimal amount, DateOnly businessDate, CancellationToken cancellationToken = default);
    Task SaveTransactionAsync(TransactionLog log, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns all approved, uncleared transactions for the given business date and settlement profile.
    /// "Approved" = ResponseCode in {"00","08","10","11"}. "Uncleared" = IsCleared = false.
    /// Used by the clearing engine to build clearing batches.
    /// </summary>
    Task<IReadOnlyList<TransactionLog>> GetUnclearedTransactionsAsync(DateOnly businessDate, string settlementProfile, CancellationToken cancellationToken = default);

    /// <summary>
    /// Marks a batch of transactions as cleared and links them to a clearing batch.
    /// Called by the clearing engine after the ClearingBatch is committed.
    /// </summary>
    Task MarkTransactionsClearedAsync(IReadOnlyCollection<string> correlationIds, Guid clearingBatchId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns ALL approved transactions for the given business date, regardless of clearing status.
    /// Used by the reconciliation engine which must check both cleared and uncleared transactions.
    /// "Approved" = ResponseCode in {"00","08","10","11"} and Mti in {"0200","0210"}.
    /// </summary>
    Task<IReadOnlyList<TransactionLog>> GetApprovedTransactionsByDateAsync(DateOnly businessDate, CancellationToken cancellationToken = default);
}

public interface INodeRepository
{
    Task<SourceNode?> GetSourceNodeAsync(string nodeId, CancellationToken cancellationToken = default);
    Task<SinkNode?> GetSinkNodeAsync(Guid sinkNodeId, CancellationToken cancellationToken = default);
}

public interface IRouteRepository
{
    /// <summary>Legacy BIN-only lookup retained for older callers and tests.</summary>
    Task<RouteDefinition?> GetRouteByBinAsync(string binPrefix, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns the best active route using Tier-1 switch routing criteria: country, MCC,
    /// currency, device, interchange, card range, institution, product, network and account number.
    /// </summary>
    Task<RouteDefinition?> GetBestRouteAsync(RouteMatchCriteria criteria, CancellationToken cancellationToken = default);

    Task<Scheme?> GetSchemeForSourceAndRouteAsync(Guid sourceNodeId, Guid routeId, CancellationToken cancellationToken = default);
    Task<Fee?> GetFeeAsync(Guid feeId, CancellationToken cancellationToken = default);
}

public interface ISinkClient
{
    Task<IsoMessage> SendAsync(IsoMessage message, SinkNode sinkNode, CancellationToken cancellationToken = default);
}

public interface IAuditLogger
{
    void LogTransaction(TransactionLog log);
    void LogSecurity(string correlationId, string eventName, string message);
    void LogAdminAudit(string correlationId, string actor, string action, string oldValue, string newValue, string reason, string ticketReference);
    void LogSystem(string correlationId, string eventName, Exception? exception = null);
    void LogReconciliation(string correlationId, string settlementProfile, string status, string details);
}

public interface IReversalRepository
{
    Task<ReversalWorkItem?> TryStartReversalAsync(string originalDataElement, string correlationId, CancellationToken cancellationToken = default);
    Task<IReadOnlyCollection<ReversalWorkItem>> GetDueReversalsAsync(DateTimeOffset now, int maxAttempts, CancellationToken cancellationToken = default);
    Task MarkAcceptedAsync(ReversalWorkItem item, string responseCode, CancellationToken cancellationToken = default);
    Task MarkRejectedAsync(ReversalWorkItem item, string responseCode, CancellationToken cancellationToken = default);
    Task ScheduleRetryAsync(ReversalWorkItem item, string reason, DateTimeOffset nextAttemptAt, CancellationToken cancellationToken = default);
    Task MarkFailedAsync(ReversalWorkItem item, string reason, CancellationToken cancellationToken = default);
}

public interface IReplayCache
{
    bool TryAccept(string replayKey, TimeSpan ttl);
}

public interface INodeRateLimiter
{
    bool TryAcquire(string nodeId, int tpsLimit, out string reason);
}

public interface ISlaMetrics
{
    void RecordLatency(string sinkNodeId, TimeSpan latency);
    void RecordResponseCode(string sourceNodeId, string sinkNodeId, string responseCode);
    void RecordReversal(string sinkNodeId, ReversalState state);
}

public sealed record ReversalWorkItem(
    Guid OriginalTransactionId,
    string OriginalDataElement,
    IsoMessage ReversalMessage,
    Guid SinkNodeId,
    string CorrelationId,
    int AttemptCount,
    ReversalState State)
{
    public DateTimeOffset NextAttemptAt { get; init; } = DateTimeOffset.UtcNow;
}
