-- ============================================================
-- v44.3A Enterprise Settings completeness
-- Field-level definitions across all control-plane domains
-- PostgreSQL version
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;

-- ============================================================
-- Temporary definition table
-- ============================================================

CREATE TEMP TABLE tmp_configuration_definitions
(
    domaincode          varchar(64),
    key                 varchar(160),
    displayname         varchar(160),
    description         varchar(1024),
    valuetype           varchar(32),
    defaultvalue        text,
    allowedvaluesjson   text,
    minimumvalue        numeric(28,8),
    maximumvalue        numeric(28,8),
    sensitivity         varchar(32),
    reloadpolicy        varchar(32),
    requiresapproval    boolean,
    issecret            boolean,
    issensitive         boolean,
    productionlocked    boolean,
    validationpattern   varchar(512),
    displayorder        integer
);

-- ============================================================
-- Configuration definitions
-- ============================================================

INSERT INTO tmp_configuration_definitions
(
    domaincode,
    key,
    displayname,
    description,
    valuetype,
    defaultvalue,
    allowedvaluesjson,
    minimumvalue,
    maximumvalue,
    sensitivity,
    reloadpolicy,
    requiresapproval,
    issecret,
    issensitive,
    productionlocked,
    validationpattern,
    displayorder
)
VALUES

(
    'general',
    'InstitutionName',
    'Institution Name',
    'Display/legal institution name',
    'String',
    'BankSwitch Institution',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'general',
    'CountryCode',
    'Country Code',
    'ISO 3166-1 alpha-2 country code',
    'String',
    'IN',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    '^[A-Z]{2}$',
    60
),
(
    'general',
    'BusinessDate',
    'Business Date',
    'Authoritative banking business date in YYYY-MM-DD',
    'String',
    '2026-01-01',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    '^\d{4}-\d{2}-\d{2}$',
    70
),
(
    'general',
    'DefaultLanguage',
    'Default Language',
    'Default operator locale',
    'String',
    'en-IN',
    NULL,
    NULL,
    NULL,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    80
),

(
    'api',
    'ConnectionTimeoutSeconds',
    'Connection Timeout',
    'Outbound API connection timeout',
    'Integer',
    '10',
    NULL,
    1,
    120,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'api',
    'RetryBackoffMs',
    'Retry Backoff',
    'Base retry backoff milliseconds',
    'Integer',
    '250',
    NULL,
    10,
    30000,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'api',
    'MaxConcurrentRequests',
    'Max Concurrent Requests',
    'Administrative API concurrency limit',
    'Integer',
    '500',
    NULL,
    10,
    10000,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'api',
    'MaxRequestBodyBytes',
    'Max Request Body',
    'Maximum API request body size bytes',
    'Integer',
    '1048576',
    NULL,
    1024,
    104857600,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),

(
    'realtime',
    'ReconnectSeconds',
    'Reconnect Interval',
    'SignalR reconnect interval',
    'Integer',
    '5',
    NULL,
    1,
    300,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'realtime',
    'MaxReconnectAttempts',
    'Max Reconnect Attempts',
    'Maximum realtime reconnect attempts',
    'Integer',
    '10',
    NULL,
    1,
    100,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'realtime',
    'EventBufferSize',
    'Event Buffer Size',
    'Client realtime event buffer limit',
    'Integer',
    '1000',
    NULL,
    100,
    100000,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'database',
    'ConnectionStringRef',
    'Connection String Reference',
    'Vault reference to SQL connection string',
    'SecretReference',
    'vault://bankswitch/sql/connection',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    NULL,
    40
),
(
    'database',
    'MinPoolSize',
    'SQL Min Pool Size',
    'Minimum ADO.NET pool size',
    'Integer',
    '10',
    NULL,
    0,
    500,
    'Sensitive',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'database',
    'DeadlockRetryCount',
    'Deadlock Retry Count',
    'Database deadlock retry count',
    'Integer',
    '3',
    NULL,
    0,
    20,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),
(
    'database',
    'IsolationLevel',
    'Write Isolation Level',
    'Default financial write isolation level',
    'Enum',
    'ReadCommitted',
    '["ReadCommitted","RepeatableRead","Serializable","Snapshot"]',
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    70
),

(
    'transactions',
    'FinancialTimeoutSeconds',
    'Financial Timeout',
    '0200 transaction timeout',
    'Integer',
    '30',
    NULL,
    1,
    180,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'transactions',
    'ReversalTimeoutSeconds',
    'Reversal Timeout',
    'Reversal response timeout',
    'Integer',
    '30',
    NULL,
    1,
    180,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),
(
    'transactions',
    'SafRetrySeconds',
    'SAF Retry Interval',
    'Store-and-forward retry interval',
    'Integer',
    '60',
    NULL,
    5,
    3600,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    70
),
(
    'transactions',
    'MaxSafRetries',
    'Maximum SAF Retries',
    'Maximum SAF delivery attempts',
    'Integer',
    '10',
    NULL,
    1,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    80
),
(
    'transactions',
    'IdempotencyTtlSeconds',
    'Idempotency TTL',
    'Distributed idempotency retention',
    'Integer',
    '86400',
    NULL,
    60,
    604800,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    90
),
(
    'transactions',
    'StipEnabled',
    'STIP Enabled',
    'Enable stand-in transaction processing',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    100
),

(
    'iso8583',
    'IsoVersion',
    'ISO Version',
    'Default ISO 8583 dialect',
    'Enum',
    '1987',
    '["1987","1993","2003"]',
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'iso8583',
    'CharacterEncoding',
    'Character Encoding',
    'Network message character encoding',
    'Enum',
    'ASCII',
    '["ASCII","EBCDIC","UTF-8"]',
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'iso8583',
    'BitmapEncoding',
    'Bitmap Encoding',
    'Bitmap encoding format',
    'Enum',
    'ASCIIHEX',
    '["ASCIIHEX","BINARY"]',
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'iso8583',
    'TpduEnabled',
    'TPDU Enabled',
    'Enable TPDU header processing',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),
(
    'iso8583',
    'Field55MaxLength',
    'DE55 Max Length',
    'Maximum EMV field 55 length',
    'Integer',
    '999',
    NULL,
    1,
    4096,
    'Sensitive',
    'ServiceRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    70
),

(
    'routing',
    'Strategy',
    'Routing Strategy',
    'Route selection strategy',
    'Enum',
    'Priority',
    '["Priority","Weighted","LeastCost","HealthAware"]',
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'routing',
    'HealthThresholdPercent',
    'Health Threshold',
    'Minimum destination health percent',
    'Integer',
    '95',
    NULL,
    1,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'routing',
    'CacheSeconds',
    'Route Cache TTL',
    'Route rules cache interval',
    'Integer',
    '30',
    NULL,
    0,
    3600,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'routing',
    'SimulationEnabled',
    'Route Simulation',
    'Allow route simulation in admin',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'network-hosts',
    'VisaPrimaryEndpoint',
    'Visa Primary Endpoint',
    'Visa authorization endpoint',
    'Uri',
    'https://visa.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'network-hosts',
    'MastercardPrimaryEndpoint',
    'Mastercard Primary Endpoint',
    'Mastercard authorization endpoint',
    'Uri',
    'https://mastercard.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'network-hosts',
    'RupayPrimaryEndpoint',
    'RuPay Primary Endpoint',
    'RuPay/NPCI authorization endpoint',
    'Uri',
    'https://rupay.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'network-hosts',
    'ReconnectSeconds',
    'Reconnect Interval',
    'Network connection reconnect interval',
    'Integer',
    '10',
    NULL,
    1,
    600,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),
(
    'network-hosts',
    'SignOnIntervalSeconds',
    'Sign-On Interval',
    'Network sign-on refresh interval',
    'Integer',
    '300',
    NULL,
    10,
    86400,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    70
),
(
    'network-hosts',
    'CertificateRef',
    'Network Certificate Reference',
    'Certificate inventory reference for scheme TLS',
    'CertificateReference',
    'SCHEME-TLS-CERT',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    NULL,
    80
),

(
    'atm',
    'DefaultProtocol',
    'Default ATM Protocol',
    'Default ATM terminal protocol',
    'Enum',
    'NDC+',
    '["NDC","NDC+","DDC","XFS","APTRA"]',
    NULL,
    NULL,
    'Sensitive',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'atm',
    'CommandTimeoutSeconds',
    'ATM Command Timeout',
    'Terminal command timeout',
    'Integer',
    '30',
    NULL,
    1,
    300,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'atm',
    'EjUploadMinutes',
    'EJ Upload Interval',
    'Electronic journal upload interval',
    'Integer',
    '15',
    NULL,
    1,
    1440,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'atm',
    'ScreenPackageVersion',
    'Screen Package Version',
    'Active ATM screen package version',
    'String',
    '1.0.0',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'pos',
    'HeartbeatSeconds',
    'POS Heartbeat',
    'POS terminal heartbeat interval',
    'Integer',
    '60',
    NULL,
    5,
    3600,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'pos',
    'CommandTimeoutSeconds',
    'POS Command Timeout',
    'POS remote command timeout',
    'Integer',
    '30',
    NULL,
    1,
    300,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'pos',
    'ContactlessOfflineEnabled',
    'Offline Contactless',
    'Enable controlled offline contactless',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'pos',
    'TipAdjustmentEnabled',
    'Tip Adjustment',
    'Enable post-auth tip adjustment',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'pos',
    'CashAtPosEnabled',
    'Cash@POS',
    'Enable Cash@POS acquiring',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),

(
    'merchant',
    'DefaultMdrPercent',
    'Default MDR %',
    'Default merchant discount rate percent',
    'Decimal',
    '2.0',
    NULL,
    0,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'merchant',
    'ReservePercent',
    'Reserve %',
    'Default merchant reserve percent',
    'Decimal',
    '0',
    NULL,
    0,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'merchant',
    'RefundLimit',
    'Refund Limit',
    'Default merchant refund amount limit',
    'Decimal',
    '100000',
    NULL,
    0,
    100000000,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'cards',
    'DefaultExpiryMonths',
    'Default Card Expiry',
    'Default card expiry months',
    'Integer',
    '60',
    NULL,
    1,
    120,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'cards',
    'ContactlessLimit',
    'Contactless Limit',
    'Default contactless limit',
    'Decimal',
    '5000',
    NULL,
    0,
    100000,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'cards',
    'InternationalEnabled',
    'International Usage',
    'Default international card usage',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'cards',
    'VirtualCardEnabled',
    'Virtual Cards',
    'Enable virtual card issuance',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'hsm',
    'PrimaryEndpoint',
    'Primary HSM Endpoint',
    'Primary HSM service/device endpoint',
    'String',
    'hsm-primary:1500',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    NULL,
    30
),
(
    'hsm',
    'SecondaryEndpoint',
    'Secondary HSM Endpoint',
    'Secondary HSM service/device endpoint',
    'String',
    'hsm-secondary:1500',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ServiceRestart',
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    NULL,
    40
),
(
    'hsm',
    'CommandTimeoutSeconds',
    'HSM Command Timeout',
    'HSM command timeout',
    'Integer',
    '5',
    NULL,
    1,
    60,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'hsm',
    'Tr31Enabled',
    'TR-31 Enabled',
    'Require TR-31 key blocks',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),
(
    'hsm',
    'Tr34Enabled',
    'TR-34 Enabled',
    'Allow TR-34 remote key loading',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    70
),

(
    'fraud',
    'HighScoreThreshold',
    'High Risk Score',
    'High risk score threshold',
    'Integer',
    '75',
    NULL,
    1,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'fraud',
    'VelocityWindowMinutes',
    'Velocity Window',
    'Default velocity window minutes',
    'Integer',
    '10',
    NULL,
    1,
    1440,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'fraud',
    'AutoBlockCritical',
    'Auto Block Critical',
    'Automatically block critical-risk events',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'aml',
    'SanctionsEnabled',
    'Sanctions Screening',
    'Enable sanctions screening',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'aml',
    'PepEnabled',
    'PEP Screening',
    'Enable PEP screening',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'aml',
    'AutoCaseThreshold',
    'AML Auto Case Score',
    'Score triggering automatic AML case',
    'Integer',
    '80',
    NULL,
    1,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'aml',
    'ProviderEndpoint',
    'AML Provider Endpoint',
    'External screening provider endpoint',
    'Uri',
    'https://aml.invalid',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'settlement',
    'AutoSettlementEnabled',
    'Auto Settlement',
    'Enable automatic settlement posting',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'settlement',
    'DefaultCurrency',
    'Settlement Currency',
    'Default settlement currency',
    'String',
    'INR',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    '^[A-Z]{3}$',
    30
),
(
    'settlement',
    'HolidayCalendar',
    'Holiday Calendar',
    'Settlement holiday calendar identifier',
    'String',
    'IN-BANKING',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'gl',
    'AutoPostingEnabled',
    'Automatic GL Posting',
    'Automatically post balanced journals',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'gl',
    'SuspenseAccount',
    'Suspense Account',
    'Default GL suspense account code',
    'String',
    'SUSPENSE',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'gl',
    'PeriodCloseApprovalRequired',
    'Period Close Approval',
    'Require checker for accounting period close',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    NULL,
    40
),

(
    'reconciliation',
    'AutoMatchEnabled',
    'Automatic Matching',
    'Enable automatic reconciliation matching',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'reconciliation',
    'DateToleranceDays',
    'Date Tolerance Days',
    'Date tolerance for automatic matching',
    'Integer',
    '1',
    NULL,
    0,
    30,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'reconciliation',
    'ExceptionAgeHours',
    'Exception Ageing',
    'Hours before unmatched item escalation',
    'Integer',
    '24',
    NULL,
    1,
    720,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'disputes',
    'ChargebackSlaDays',
    'Chargeback SLA',
    'Chargeback SLA days',
    'Integer',
    '7',
    NULL,
    1,
    180,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'disputes',
    'RepresentmentSlaDays',
    'Representment SLA',
    'Representment SLA days',
    'Integer',
    '7',
    NULL,
    1,
    180,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'disputes',
    'EvidenceRetentionDays',
    'Evidence Retention',
    'Dispute evidence retention days',
    'Integer',
    '2555',
    NULL,
    365,
    3650,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'cbs',
    'SecondaryEndpoint',
    'CBS Secondary Endpoint',
    'Secondary CBS integration endpoint',
    'Uri',
    'https://cbs-dr.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'cbs',
    'TimeoutSeconds',
    'CBS Timeout',
    'Core banking request timeout',
    'Integer',
    '10',
    NULL,
    1,
    120,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'cbs',
    'RetryCount',
    'CBS Retry Count',
    'Core banking transient retry count',
    'Integer',
    '2',
    NULL,
    0,
    10,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'cbs',
    'CircuitBreakerFailures',
    'CBS Circuit Breaker',
    'Failure threshold before circuit opens',
    'Integer',
    '5',
    NULL,
    1,
    100,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'enterprise',
    'EsbEndpoint',
    'ESB Endpoint',
    'Enterprise service bus endpoint',
    'Uri',
    'https://esb.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'enterprise',
    'AcsEndpoint',
    'ACS / 3DS Endpoint',
    'ACS/3DS integration endpoint',
    'Uri',
    'https://acs.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'enterprise',
    'FrmEndpoint',
    'FRM Endpoint',
    'Fraud risk manager endpoint',
    'Uri',
    'https://frm.invalid',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ConnectionRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'enterprise',
    'DwhExportEnabled',
    'DWH Export',
    'Enable warehouse feed generation',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'certification',
    'EvidenceRetentionDays',
    'Evidence Retention',
    'Certification evidence retention days',
    'Integer',
    '2555',
    NULL,
    365,
    3650,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'certification',
    'FuzzTestingEnabled',
    'Fuzz Testing',
    'Allow controlled certification fuzz testing',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'certification',
    'EnduranceMinutes',
    'Endurance Test Duration',
    'Default certification endurance duration minutes',
    'Integer',
    '60',
    NULL,
    1,
    10080,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'security',
    'SessionTimeoutMinutes',
    'Session Timeout',
    'Privileged admin session timeout',
    'Integer',
    '15',
    NULL,
    5,
    480,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),
(
    'security',
    'LoginAttemptLimit',
    'Login Attempt Limit',
    'Failed login attempts before lockout',
    'Integer',
    '5',
    NULL,
    3,
    20,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    60
),
(
    'security',
    'LockoutMinutes',
    'Account Lockout',
    'Account lockout duration minutes',
    'Integer',
    '30',
    NULL,
    1,
    1440,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    70
),
(
    'security',
    'IpAllowListEnabled',
    'Admin IP Allowlist',
    'Enable administrative IP allowlisting',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    80
),

(
    'rbac',
    'PrivilegedRoleReviewDays',
    'Privileged Role Review',
    'Days between privileged access reviews',
    'Integer',
    '90',
    NULL,
    1,
    365,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    10
),
(
    'rbac',
    'DormantUserDays',
    'Dormant User Threshold',
    'Disable/review users inactive for this many days',
    'Integer',
    '45',
    NULL,
    1,
    365,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'rbac',
    'ExportPermissionRequired',
    'Export Permission',
    'Require explicit role permission for data export',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),

(
    'maker-checker',
    'ApprovalExpiryHours',
    'Approval Expiry',
    'Hours before pending approval expires',
    'Integer',
    '24',
    NULL,
    1,
    168,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'maker-checker',
    'EmergencyOverrideEnabled',
    'Emergency Override',
    'Permit emergency controlled override',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    NULL,
    30
),
(
    'maker-checker',
    'TicketRequired',
    'Change Ticket Required',
    'Require ticket reference for configuration changes',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'audit',
    'SiemForwardingEnabled',
    'SIEM Forwarding',
    'Forward security/admin audit events to SIEM',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'audit',
    'HashChainEnabled',
    'Audit Hash Chain',
    'Enable tamper-evident audit chaining',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    NULL,
    30
),
(
    'audit',
    'ExportApprovalRequired',
    'Audit Export Approval',
    'Require checker before audit export',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'compliance',
    'PciEvidenceRequired',
    'PCI Evidence Required',
    'Require PCI evidence completion for release',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    NULL,
    10
),
(
    'compliance',
    'RbiEvidenceRequired',
    'RBI Evidence Required',
    'Require RBI control evidence for production release',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    NULL,
    20
),
(
    'compliance',
    'EvidenceReviewDays',
    'Evidence Review Cycle',
    'Maximum compliance evidence review interval days',
    'Integer',
    '90',
    NULL,
    1,
    365,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),

(
    'monitoring',
    'TpsWarning',
    'TPS Warning',
    'TPS warning threshold',
    'Integer',
    '5000',
    NULL,
    1,
    100000,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'monitoring',
    'DeclineRateCriticalPercent',
    'Decline Rate Critical',
    'Critical decline rate percent',
    'Decimal',
    '20',
    NULL,
    0,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'monitoring',
    'QueueDepthCritical',
    'Queue Depth Critical',
    'Critical processing queue depth',
    'Integer',
    '3000',
    NULL,
    1,
    100000,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'monitoring',
    'AvailabilitySlaPercent',
    'Availability SLA',
    'Required platform availability percentage',
    'Decimal',
    '99.95',
    NULL,
    90,
    100,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'alerts',
    'EmailEnabled',
    'Email Alerts',
    'Enable email operational alerts',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Operational',
    'HotReload',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'alerts',
    'SmsEnabled',
    'SMS Alerts',
    'Enable SMS critical alerts',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'alerts',
    'CriticalEscalationMinutes',
    'Critical Escalation',
    'Minutes before critical alert escalates',
    'Integer',
    '5',
    NULL,
    1,
    120,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),

(
    'observability',
    'OpenTelemetryEnabled',
    'OpenTelemetry',
    'Enable OpenTelemetry tracing/metrics',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'observability',
    'TraceSamplingPercent',
    'Trace Sampling %',
    'OpenTelemetry trace sample percentage',
    'Integer',
    '10',
    NULL,
    0,
    100,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'observability',
    'SensitiveDataMasking',
    'Sensitive Data Masking',
    'Enforce sensitive value masking in logs',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    NULL,
    40
),

(
    'dr',
    'Mode',
    'DR Mode',
    'Disaster recovery topology',
    'Enum',
    'ActivePassive',
    '["ActivePassive","ActiveActive"]',
    NULL,
    NULL,
    'Critical',
    'ClusterRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'dr',
    'AutomaticFailoverEnabled',
    'Automatic Failover',
    'Enable automatic DR failover',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'dr',
    'DrSiteCode',
    'DR Site Code',
    'Configured disaster recovery site identifier',
    'String',
    'DR1',
    NULL,
    NULL,
    NULL,
    'Critical',
    'ClusterRestart',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'retention',
    'AuditDays',
    'Audit Retention',
    'Audit event retention days',
    'Integer',
    '2555',
    NULL,
    365,
    3650,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'retention',
    'EjDays',
    'EJ Retention',
    'ATM electronic journal retention days',
    'Integer',
    '365',
    NULL,
    30,
    3650,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'retention',
    'DisputeDays',
    'Dispute Retention',
    'Dispute case/evidence retention days',
    'Integer',
    '2555',
    NULL,
    365,
    3650,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
),
(
    'retention',
    'CertificationDays',
    'Certification Retention',
    'Certification evidence retention days',
    'Integer',
    '2555',
    NULL,
    365,
    3650,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    50
),

(
    'feature-flags',
    'ProductionPercentageRolloutAllowed',
    'Production Percentage Rollout',
    'Permit percentage feature rollout in PROD',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    10
),
(
    'feature-flags',
    'RollbackOnHealthFailure',
    'Rollback On Health Failure',
    'Automatically rollback feature flag when health degrades',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),

(
    'diagnostics',
    'ProbeTimeoutSeconds',
    'Probe Timeout',
    'Maximum diagnostic dependency probe duration',
    'Integer',
    '5',
    NULL,
    1,
    60,
    'Sensitive',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    20
),
(
    'diagnostics',
    'HsmProbeEnabled',
    'HSM Probe',
    'Enable privileged HSM connectivity probe',
    'Boolean',
    'true',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    30
),
(
    'diagnostics',
    'NetworkProbeEnabled',
    'Network Host Probe',
    'Enable privileged scheme host connectivity probes',
    'Boolean',
    'false',
    NULL,
    NULL,
    NULL,
    'Critical',
    'HotReload',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    40
);

-- ============================================================
-- Merge configuration definitions
-- ============================================================

MERGE INTO dbo.configurationdefinitions AS t
USING tmp_configuration_definitions AS s
ON t.domaincode = s.domaincode
AND t.key = s.key

WHEN MATCHED THEN
    UPDATE SET
        displayname = s.displayname,
        description = s.description,
        valuetype = s.valuetype,
        defaultvalue = s.defaultvalue,
        allowedvaluesjson = s.allowedvaluesjson,
        minimumvalue = s.minimumvalue,
        maximumvalue = s.maximumvalue,
        sensitivity = s.sensitivity,
        reloadpolicy = s.reloadpolicy,
        requiresapproval = s.requiresapproval,
        issecret = s.issecret,
        issensitive = s.issensitive,
        productionlocked = s.productionlocked,
        validationpattern = s.validationpattern,
        displayorder = s.displayorder,
        enabled = TRUE

WHEN NOT MATCHED THEN
    INSERT
    (
        id,
        domaincode,
        key,
        displayname,
        description,
        valuetype,
        defaultvalue,
        allowedvaluesjson,
        minimumvalue,
        maximumvalue,
        sensitivity,
        reloadpolicy,
        requiresapproval,
        issecret,
        issensitive,
        productionlocked,
        validationpattern,
        displayorder,
        enabled
    )
    VALUES
    (
        gen_random_uuid(),
        s.domaincode,
        s.key,
        s.displayname,
        s.description,
        s.valuetype,
        s.defaultvalue,
        s.allowedvaluesjson,
        s.minimumvalue,
        s.maximumvalue,
        s.sensitivity,
        s.reloadpolicy,
        s.requiresapproval,
        s.issecret,
        s.issensitive,
        s.productionlocked,
        s.validationpattern,
        s.displayorder,
        TRUE
    );

COMMIT;