-- ============================================================
-- Migration 042 — End-to-End Transaction Processing & Failure-Recovery Certification
-- Durable unknown-outcome journal, SQL-backed stand-in velocity, certification evidence.
-- Apply after 001 through 041.
-- ============================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS dbo;

-- ============================================================
-- Transaction Recovery Snapshots
-- ============================================================

DO $$
BEGIN
    IF to_regclass('dbo.transactionrecoverysnapshots') IS NULL THEN

        CREATE TABLE dbo.transactionrecoverysnapshots
        (
            id                       uuid NOT NULL
                CONSTRAINT pk_transactionrecoverysnapshots PRIMARY KEY
                DEFAULT gen_random_uuid(),

            correlationid            varchar(64) NOT NULL,

            sourcenodeid             varchar(64) NOT NULL,

            sinknodeid               uuid NOT NULL,

            stan                     varchar(12) NOT NULL
                CONSTRAINT df_trs_stan DEFAULT '',

            rrn                      varchar(12) NOT NULL
                CONSTRAINT df_trs_rrn DEFAULT '',

            originalmti              varchar(4) NOT NULL,

            originaldataelement     varchar(42) NOT NULL,

            protectedreversalpayload text NOT NULL,

            status                   varchar(24) NOT NULL
                CONSTRAINT df_trs_status DEFAULT 'Pending',

            attemptcount             integer NOT NULL
                CONSTRAINT df_trs_attempt DEFAULT 0,

            forwardedat              timestamptz NOT NULL
                CONSTRAINT df_trs_forwarded DEFAULT (clock_timestamp()),

            nextattemptat            timestamptz NOT NULL
                CONSTRAINT df_trs_next DEFAULT (clock_timestamp()),

            resolvedat               timestamptz NULL,

            lastresponsecode         varchar(8) NOT NULL
                CONSTRAINT df_trs_response DEFAULT '',

            lasterror                varchar(1000) NOT NULL
                CONSTRAINT df_trs_error DEFAULT '',

            updatedat                timestamptz NOT NULL
                CONSTRAINT df_trs_updated DEFAULT (clock_timestamp()),

            rowversion               bytea NOT NULL,

            CONSTRAINT ux_transactionrecoverysnapshots_correlationid
                UNIQUE (correlationid),

            CONSTRAINT ck_transactionrecoverysnapshots_status
                CHECK (status IN
                    ('Pending', 'TimedOut', 'RetryScheduled',
                     'Reversed', 'Resolved', 'Failed')),

            CONSTRAINT ck_transactionrecoverysnapshots_attemptcount
                CHECK (attemptcount >= 0),

            CONSTRAINT ck_transactionrecoverysnapshots_ode
                CHECK (length(originaldataelement) = 42)
        );

    END IF;
END
$$;


-- ============================================================
-- Transaction Recovery Snapshot Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS ix_trs_due
    ON dbo.transactionrecoverysnapshots
    (status, nextattemptat, forwardedat, attemptcount)
    INCLUDE (correlationid, sinknodeid, stan, sourcenodeid);


CREATE INDEX IF NOT EXISTS ix_trs_sinknode
    ON dbo.transactionrecoverysnapshots
    (sinknodeid, status, forwardedat);


-- ============================================================
-- Transaction Recovery Snapshots → SinkNodes FK
-- ============================================================

DO $$
BEGIN
    IF to_regclass('dbo.transactionrecoverysnapshots') IS NOT NULL
       AND to_regclass('dbo.sinknodes') IS NOT NULL
       AND NOT EXISTS
       (
           SELECT 1
           FROM pg_constraint
           WHERE conname = 'fk_transactionrecoverysnapshots_sinknodes'
             AND conrelid = 'dbo.transactionrecoverysnapshots'::regclass
       )
    THEN

        ALTER TABLE dbo.transactionrecoverysnapshots
            ADD CONSTRAINT fk_transactionrecoverysnapshots_sinknodes
            FOREIGN KEY (sinknodeid)
            REFERENCES dbo.sinknodes(id);

    END IF;
END
$$;


-- ============================================================
-- Durable stand-in velocity history.
-- The PAN is represented only by keyed hash.
-- ============================================================

DO $$
BEGIN
    IF to_regclass('dbo.standinvelocityevents') IS NULL THEN

        CREATE TABLE dbo.standinvelocityevents
        (
            id         bigint GENERATED BY DEFAULT AS IDENTITY
                CONSTRAINT pk_standinvelocityevents PRIMARY KEY,

            panhash    varchar(128) NOT NULL,

            binprefix  varchar(8) NOT NULL
                CONSTRAINT df_sive_binprefix DEFAULT '',

            occurredat timestamptz NOT NULL
                CONSTRAINT df_sive_occurredat DEFAULT (clock_timestamp())
        );

    END IF;
END
$$;


CREATE INDEX IF NOT EXISTS ix_sive_panhash_bin_occurredat
    ON dbo.standinvelocityevents
    (panhash, binprefix, occurredat);


-- ============================================================
-- Certification evidence:
-- deliberately stores no PAN, PIN, CVV or cryptographic key material.
-- ============================================================

DO $$
BEGIN
    IF to_regclass('dbo.transactionrecoverycertificationruns') IS NULL THEN

        CREATE TABLE dbo.transactionrecoverycertificationruns
        (
            runid           uuid NOT NULL
                CONSTRAINT pk_transactionrecoverycertificationruns
                PRIMARY KEY,

            environment     varchar(32) NOT NULL,

            buildversion    varchar(64) NOT NULL
                CONSTRAINT df_trcr_build DEFAULT '',

            startedat       timestamptz NOT NULL,

            completedat     timestamptz NULL,

            totalcases      integer NOT NULL
                CONSTRAINT df_trcr_total DEFAULT 0,

            passedcases     integer NOT NULL
                CONSTRAINT df_trcr_passed DEFAULT 0,

            failedcases     integer NOT NULL
                CONSTRAINT df_trcr_failed DEFAULT 0,

            skippedcases    integer NOT NULL
                CONSTRAINT df_trcr_skipped DEFAULT 0,

            evidencesha256  char(64) NOT NULL
                CONSTRAINT df_trcr_hash DEFAULT '',

            createdby       varchar(128) NOT NULL
                CONSTRAINT df_trcr_createdby DEFAULT 'SYSTEM',

            createdat       timestamptz NOT NULL
                CONSTRAINT df_trcr_createdat DEFAULT (clock_timestamp())
        );

    END IF;
END
$$;


-- ============================================================
-- Transaction Recovery Certification Case Results
-- ============================================================

DO $$
BEGIN
    IF to_regclass('dbo.transactionrecoverycertificationcaseresults') IS NULL THEN

        CREATE TABLE dbo.transactionrecoverycertificationcaseresults
        (
            id              uuid NOT NULL
                CONSTRAINT pk_transactionrecoverycertificationcaseresults
                PRIMARY KEY
                DEFAULT gen_random_uuid(),

            runid           uuid NOT NULL,

            caseid          varchar(64) NOT NULL,

            category        varchar(64) NOT NULL,

            description     varchar(500) NOT NULL,

            outcome         varchar(16) NOT NULL,

            durationms      bigint NOT NULL
                CONSTRAINT df_trcc_duration DEFAULT 0,

            evidence        text NOT NULL
                CONSTRAINT df_trcc_evidence DEFAULT '',

            evidencesha256  char(64) NOT NULL
                CONSTRAINT df_trcc_hash DEFAULT '',

            completedat     timestamptz NOT NULL,

            CONSTRAINT fk_transactionrecoverycertificationcaseresults_run
                FOREIGN KEY (runid)
                REFERENCES dbo.transactionrecoverycertificationruns(runid),

            CONSTRAINT ux_transactionrecoverycertificationcaseresults_runcase
                UNIQUE (runid, caseid),

            CONSTRAINT ck_transactionrecoverycertificationcaseresults_outcome
                CHECK (outcome IN ('Pass', 'Fail', 'Skipped'))
        );

    END IF;
END
$$;


CREATE INDEX IF NOT EXISTS ix_trcc_run_outcome
    ON dbo.transactionrecoverycertificationcaseresults
    (runid, outcome, completedat);


-- ============================================================
-- Strengthen recovery lookup and audit queries on lifecycle state.
-- ============================================================

CREATE INDEX IF NOT EXISTS ix_tls_correlationid_state_at
    ON dbo.transactionlifecyclestates
    (correlationid, newstate, occurredat DESC)
    INCLUDE (stan, sourcenodeid, previousstate, reason, latencyfromreceivedms);


CREATE INDEX IF NOT EXISTS ix_preauthrecords_stan_source
    ON dbo.preauthrecords
    (stan, sourcenodeid, status, createdat DESC);


COMMIT;