SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- v44.3A Enterprise Settings completeness: field-level definitions across all control-plane domains.
DECLARE @defs TABLE(
 DomainCode nvarchar(64), [Key] nvarchar(160), DisplayName nvarchar(160), Description nvarchar(1024),
 ValueType nvarchar(32), DefaultValue nvarchar(max), AllowedValuesJson nvarchar(max), MinimumValue decimal(28,8), MaximumValue decimal(28,8),
 Sensitivity nvarchar(32), ReloadPolicy nvarchar(32), RequiresApproval bit, IsSecret bit, IsSensitive bit, ProductionLocked bit, ValidationPattern nvarchar(512), DisplayOrder int);
INSERT INTO @defs VALUES
(N'general',N'InstitutionName',N'Institution Name',N'Display/legal institution name',N'String',N'BankSwitch Institution',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'general',N'CountryCode',N'Country Code',N'ISO 3166-1 alpha-2 country code',N'String',N'IN',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,N'^[A-Z]{2}$',60),
(N'general',N'BusinessDate',N'Business Date',N'Authoritative banking business date in YYYY-MM-DD',N'String',N'2026-01-01',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,N'^\d{4}-\d{2}-\d{2}$',70),
(N'general',N'DefaultLanguage',N'Default Language',N'Default operator locale',N'String',N'en-IN',NULL,NULL,NULL,N'Operational',N'HotReload',0,0,0,0,NULL,80),
(N'api',N'ConnectionTimeoutSeconds',N'Connection Timeout',N'Outbound API connection timeout',N'Integer',N'10',NULL,1,120,N'Operational',N'HotReload',0,0,0,0,NULL,30),
(N'api',N'RetryBackoffMs',N'Retry Backoff',N'Base retry backoff milliseconds',N'Integer',N'250',NULL,10,30000,N'Operational',N'HotReload',0,0,0,0,NULL,40),
(N'api',N'MaxConcurrentRequests',N'Max Concurrent Requests',N'Administrative API concurrency limit',N'Integer',N'500',NULL,10,10000,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'api',N'MaxRequestBodyBytes',N'Max Request Body',N'Maximum API request body size bytes',N'Integer',N'1048576',NULL,1024,104857600,N'Sensitive',N'HotReload',1,0,0,0,NULL,60),
(N'realtime',N'ReconnectSeconds',N'Reconnect Interval',N'SignalR reconnect interval',N'Integer',N'5',NULL,1,300,N'Operational',N'HotReload',0,0,0,0,NULL,30),
(N'realtime',N'MaxReconnectAttempts',N'Max Reconnect Attempts',N'Maximum realtime reconnect attempts',N'Integer',N'10',NULL,1,100,N'Operational',N'HotReload',0,0,0,0,NULL,40),
(N'realtime',N'EventBufferSize',N'Event Buffer Size',N'Client realtime event buffer limit',N'Integer',N'1000',NULL,100,100000,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'database',N'ConnectionStringRef',N'Connection String Reference',N'Vault reference to SQL connection string',N'SecretReference',N'vault://bankswitch/sql/connection',NULL,NULL,NULL,N'Critical',N'ServiceRestart',1,1,1,0,NULL,40),
(N'database',N'MinPoolSize',N'SQL Min Pool Size',N'Minimum ADO.NET pool size',N'Integer',N'10',NULL,0,500,N'Sensitive',N'ServiceRestart',1,0,0,0,NULL,50),
(N'database',N'DeadlockRetryCount',N'Deadlock Retry Count',N'Database deadlock retry count',N'Integer',N'3',NULL,0,20,N'Sensitive',N'HotReload',1,0,0,0,NULL,60),
(N'database',N'IsolationLevel',N'Write Isolation Level',N'Default financial write isolation level',N'Enum',N'ReadCommitted',N'["ReadCommitted","RepeatableRead","Serializable","Snapshot"]',NULL,NULL,N'Critical',N'ServiceRestart',1,0,0,0,NULL,70),
(N'transactions',N'FinancialTimeoutSeconds',N'Financial Timeout',N'0200 transaction timeout',N'Integer',N'30',NULL,1,180,N'Critical',N'HotReload',1,0,0,0,NULL,50),
(N'transactions',N'ReversalTimeoutSeconds',N'Reversal Timeout',N'Reversal response timeout',N'Integer',N'30',NULL,1,180,N'Critical',N'HotReload',1,0,0,0,NULL,60),
(N'transactions',N'SafRetrySeconds',N'SAF Retry Interval',N'Store-and-forward retry interval',N'Integer',N'60',NULL,5,3600,N'Critical',N'HotReload',1,0,0,0,NULL,70),
(N'transactions',N'MaxSafRetries',N'Maximum SAF Retries',N'Maximum SAF delivery attempts',N'Integer',N'10',NULL,1,100,N'Critical',N'HotReload',1,0,0,0,NULL,80),
(N'transactions',N'IdempotencyTtlSeconds',N'Idempotency TTL',N'Distributed idempotency retention',N'Integer',N'86400',NULL,60,604800,N'Critical',N'HotReload',1,0,0,0,NULL,90),
(N'transactions',N'StipEnabled',N'STIP Enabled',N'Enable stand-in transaction processing',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,100),
(N'iso8583',N'IsoVersion',N'ISO Version',N'Default ISO 8583 dialect',N'Enum',N'1987',N'["1987","1993","2003"]',NULL,NULL,N'Critical',N'ServiceRestart',1,0,0,0,NULL,30),
(N'iso8583',N'CharacterEncoding',N'Character Encoding',N'Network message character encoding',N'Enum',N'ASCII',N'["ASCII","EBCDIC","UTF-8"]',NULL,NULL,N'Critical',N'ServiceRestart',1,0,0,0,NULL,40),
(N'iso8583',N'BitmapEncoding',N'Bitmap Encoding',N'Bitmap encoding format',N'Enum',N'ASCIIHEX',N'["ASCIIHEX","BINARY"]',NULL,NULL,N'Critical',N'ServiceRestart',1,0,0,0,NULL,50),
(N'iso8583',N'TpduEnabled',N'TPDU Enabled',N'Enable TPDU header processing',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'ServiceRestart',1,0,0,0,NULL,60),
(N'iso8583',N'Field55MaxLength',N'DE55 Max Length',N'Maximum EMV field 55 length',N'Integer',N'999',NULL,1,4096,N'Sensitive',N'ServiceRestart',1,0,0,0,NULL,70),
(N'routing',N'Strategy',N'Routing Strategy',N'Route selection strategy',N'Enum',N'Priority',N'["Priority","Weighted","LeastCost","HealthAware"]',NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'routing',N'HealthThresholdPercent',N'Health Threshold',N'Minimum destination health percent',N'Integer',N'95',NULL,1,100,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'routing',N'CacheSeconds',N'Route Cache TTL',N'Route rules cache interval',N'Integer',N'30',NULL,0,3600,N'Sensitive',N'HotReload',1,0,0,0,NULL,40),
(N'routing',N'SimulationEnabled',N'Route Simulation',N'Allow route simulation in admin',N'Boolean',N'true',NULL,NULL,NULL,N'Operational',N'HotReload',0,0,0,0,NULL,50),
(N'network-hosts',N'VisaPrimaryEndpoint',N'Visa Primary Endpoint',N'Visa authorization endpoint',N'Uri',N'https://visa.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,30),
(N'network-hosts',N'MastercardPrimaryEndpoint',N'Mastercard Primary Endpoint',N'Mastercard authorization endpoint',N'Uri',N'https://mastercard.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,40),
(N'network-hosts',N'RupayPrimaryEndpoint',N'RuPay Primary Endpoint',N'RuPay/NPCI authorization endpoint',N'Uri',N'https://rupay.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,50),
(N'network-hosts',N'ReconnectSeconds',N'Reconnect Interval',N'Network connection reconnect interval',N'Integer',N'10',NULL,1,600,N'Sensitive',N'HotReload',1,0,0,0,NULL,60),
(N'network-hosts',N'SignOnIntervalSeconds',N'Sign-On Interval',N'Network sign-on refresh interval',N'Integer',N'300',NULL,10,86400,N'Sensitive',N'HotReload',1,0,0,0,NULL,70),
(N'network-hosts',N'CertificateRef',N'Network Certificate Reference',N'Certificate inventory reference for scheme TLS',N'CertificateReference',N'SCHEME-TLS-CERT',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,1,0,NULL,80),
(N'atm',N'DefaultProtocol',N'Default ATM Protocol',N'Default ATM terminal protocol',N'Enum',N'NDC+',N'["NDC","NDC+","DDC","XFS","APTRA"]',NULL,NULL,N'Sensitive',N'ConnectionRestart',1,0,0,0,NULL,20),
(N'atm',N'CommandTimeoutSeconds',N'ATM Command Timeout',N'Terminal command timeout',N'Integer',N'30',NULL,1,300,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'atm',N'EjUploadMinutes',N'EJ Upload Interval',N'Electronic journal upload interval',N'Integer',N'15',NULL,1,1440,N'Operational',N'HotReload',0,0,0,0,NULL,40),
(N'atm',N'ScreenPackageVersion',N'Screen Package Version',N'Active ATM screen package version',N'String',N'1.0.0',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'pos',N'HeartbeatSeconds',N'POS Heartbeat',N'POS terminal heartbeat interval',N'Integer',N'60',NULL,5,3600,N'Operational',N'HotReload',0,0,0,0,NULL,20),
(N'pos',N'CommandTimeoutSeconds',N'POS Command Timeout',N'POS remote command timeout',N'Integer',N'30',NULL,1,300,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'pos',N'ContactlessOfflineEnabled',N'Offline Contactless',N'Enable controlled offline contactless',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'pos',N'TipAdjustmentEnabled',N'Tip Adjustment',N'Enable post-auth tip adjustment',N'Boolean',N'true',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'pos',N'CashAtPosEnabled',N'Cash@POS',N'Enable Cash@POS acquiring',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,60),
(N'merchant',N'DefaultMdrPercent',N'Default MDR %',N'Default merchant discount rate percent',N'Decimal',N'2.0',NULL,0,100,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'merchant',N'ReservePercent',N'Reserve %',N'Default merchant reserve percent',N'Decimal',N'0',NULL,0,100,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'merchant',N'RefundLimit',N'Refund Limit',N'Default merchant refund amount limit',N'Decimal',N'100000',NULL,0,100000000,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'cards',N'DefaultExpiryMonths',N'Default Card Expiry',N'Default card expiry months',N'Integer',N'60',NULL,1,120,N'Sensitive',N'HotReload',1,0,0,0,NULL,20),
(N'cards',N'ContactlessLimit',N'Contactless Limit',N'Default contactless limit',N'Decimal',N'5000',NULL,0,100000,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'cards',N'InternationalEnabled',N'International Usage',N'Default international card usage',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'cards',N'VirtualCardEnabled',N'Virtual Cards',N'Enable virtual card issuance',N'Boolean',N'true',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'hsm',N'PrimaryEndpoint',N'Primary HSM Endpoint',N'Primary HSM service/device endpoint',N'String',N'hsm-primary:1500',NULL,NULL,NULL,N'Critical',N'ServiceRestart',1,0,1,0,NULL,30),
(N'hsm',N'SecondaryEndpoint',N'Secondary HSM Endpoint',N'Secondary HSM service/device endpoint',N'String',N'hsm-secondary:1500',NULL,NULL,NULL,N'Critical',N'ServiceRestart',1,0,1,0,NULL,40),
(N'hsm',N'CommandTimeoutSeconds',N'HSM Command Timeout',N'HSM command timeout',N'Integer',N'5',NULL,1,60,N'Critical',N'HotReload',1,0,0,0,NULL,50),
(N'hsm',N'Tr31Enabled',N'TR-31 Enabled',N'Require TR-31 key blocks',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,60),
(N'hsm',N'Tr34Enabled',N'TR-34 Enabled',N'Allow TR-34 remote key loading',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,70),
(N'fraud',N'HighScoreThreshold',N'High Risk Score',N'High risk score threshold',N'Integer',N'75',NULL,1,100,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'fraud',N'VelocityWindowMinutes',N'Velocity Window',N'Default velocity window minutes',N'Integer',N'10',NULL,1,1440,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'fraud',N'AutoBlockCritical',N'Auto Block Critical',N'Automatically block critical-risk events',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'aml',N'SanctionsEnabled',N'Sanctions Screening',N'Enable sanctions screening',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'aml',N'PepEnabled',N'PEP Screening',N'Enable PEP screening',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'aml',N'AutoCaseThreshold',N'AML Auto Case Score',N'Score triggering automatic AML case',N'Integer',N'80',NULL,1,100,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'aml',N'ProviderEndpoint',N'AML Provider Endpoint',N'External screening provider endpoint',N'Uri',N'https://aml.invalid',NULL,NULL,NULL,N'Sensitive',N'ConnectionRestart',1,0,0,0,NULL,50),
(N'settlement',N'AutoSettlementEnabled',N'Auto Settlement',N'Enable automatic settlement posting',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'settlement',N'DefaultCurrency',N'Settlement Currency',N'Default settlement currency',N'String',N'INR',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,N'^[A-Z]{3}$',30),
(N'settlement',N'HolidayCalendar',N'Holiday Calendar',N'Settlement holiday calendar identifier',N'String',N'IN-BANKING',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,40),
(N'gl',N'AutoPostingEnabled',N'Automatic GL Posting',N'Automatically post balanced journals',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'gl',N'SuspenseAccount',N'Suspense Account',N'Default GL suspense account code',N'String',N'SUSPENSE',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'gl',N'PeriodCloseApprovalRequired',N'Period Close Approval',N'Require checker for accounting period close',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,1,NULL,40),
(N'reconciliation',N'AutoMatchEnabled',N'Automatic Matching',N'Enable automatic reconciliation matching',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'reconciliation',N'DateToleranceDays',N'Date Tolerance Days',N'Date tolerance for automatic matching',N'Integer',N'1',NULL,0,30,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'reconciliation',N'ExceptionAgeHours',N'Exception Ageing',N'Hours before unmatched item escalation',N'Integer',N'24',NULL,1,720,N'Sensitive',N'HotReload',1,0,0,0,NULL,40),
(N'disputes',N'ChargebackSlaDays',N'Chargeback SLA',N'Chargeback SLA days',N'Integer',N'7',NULL,1,180,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'disputes',N'RepresentmentSlaDays',N'Representment SLA',N'Representment SLA days',N'Integer',N'7',NULL,1,180,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'disputes',N'EvidenceRetentionDays',N'Evidence Retention',N'Dispute evidence retention days',N'Integer',N'2555',NULL,365,3650,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'cbs',N'SecondaryEndpoint',N'CBS Secondary Endpoint',N'Secondary CBS integration endpoint',N'Uri',N'https://cbs-dr.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,20),
(N'cbs',N'TimeoutSeconds',N'CBS Timeout',N'Core banking request timeout',N'Integer',N'10',NULL,1,120,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'cbs',N'RetryCount',N'CBS Retry Count',N'Core banking transient retry count',N'Integer',N'2',NULL,0,10,N'Sensitive',N'HotReload',1,0,0,0,NULL,40),
(N'cbs',N'CircuitBreakerFailures',N'CBS Circuit Breaker',N'Failure threshold before circuit opens',N'Integer',N'5',NULL,1,100,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'enterprise',N'EsbEndpoint',N'ESB Endpoint',N'Enterprise service bus endpoint',N'Uri',N'https://esb.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,20),
(N'enterprise',N'AcsEndpoint',N'ACS / 3DS Endpoint',N'ACS/3DS integration endpoint',N'Uri',N'https://acs.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,30),
(N'enterprise',N'FrmEndpoint',N'FRM Endpoint',N'Fraud risk manager endpoint',N'Uri',N'https://frm.invalid',NULL,NULL,NULL,N'Critical',N'ConnectionRestart',1,0,0,0,NULL,40),
(N'enterprise',N'DwhExportEnabled',N'DWH Export',N'Enable warehouse feed generation',N'Boolean',N'true',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,50),
(N'certification',N'EvidenceRetentionDays',N'Evidence Retention',N'Certification evidence retention days',N'Integer',N'2555',NULL,365,3650,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'certification',N'FuzzTestingEnabled',N'Fuzz Testing',N'Allow controlled certification fuzz testing',N'Boolean',N'true',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'certification',N'EnduranceMinutes',N'Endurance Test Duration',N'Default certification endurance duration minutes',N'Integer',N'60',NULL,1,10080,N'Sensitive',N'HotReload',1,0,0,0,NULL,40),
(N'security',N'SessionTimeoutMinutes',N'Session Timeout',N'Privileged admin session timeout',N'Integer',N'15',NULL,5,480,N'Critical',N'HotReload',1,0,0,0,NULL,50),
(N'security',N'LoginAttemptLimit',N'Login Attempt Limit',N'Failed login attempts before lockout',N'Integer',N'5',NULL,3,20,N'Critical',N'HotReload',1,0,0,0,NULL,60),
(N'security',N'LockoutMinutes',N'Account Lockout',N'Account lockout duration minutes',N'Integer',N'30',NULL,1,1440,N'Critical',N'HotReload',1,0,0,0,NULL,70),
(N'security',N'IpAllowListEnabled',N'Admin IP Allowlist',N'Enable administrative IP allowlisting',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,80),
(N'rbac',N'PrivilegedRoleReviewDays',N'Privileged Role Review',N'Days between privileged access reviews',N'Integer',N'90',NULL,1,365,N'Critical',N'HotReload',1,0,0,0,NULL,10),
(N'rbac',N'DormantUserDays',N'Dormant User Threshold',N'Disable/review users inactive for this many days',N'Integer',N'45',NULL,1,365,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'rbac',N'ExportPermissionRequired',N'Export Permission',N'Require explicit role permission for data export',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'maker-checker',N'ApprovalExpiryHours',N'Approval Expiry',N'Hours before pending approval expires',N'Integer',N'24',NULL,1,168,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'maker-checker',N'EmergencyOverrideEnabled',N'Emergency Override',N'Permit emergency controlled override',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,1,NULL,30),
(N'maker-checker',N'TicketRequired',N'Change Ticket Required',N'Require ticket reference for configuration changes',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'audit',N'SiemForwardingEnabled',N'SIEM Forwarding',N'Forward security/admin audit events to SIEM',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'audit',N'HashChainEnabled',N'Audit Hash Chain',N'Enable tamper-evident audit chaining',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,1,NULL,30),
(N'audit',N'ExportApprovalRequired',N'Audit Export Approval',N'Require checker before audit export',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'compliance',N'PciEvidenceRequired',N'PCI Evidence Required',N'Require PCI evidence completion for release',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,1,NULL,10),
(N'compliance',N'RbiEvidenceRequired',N'RBI Evidence Required',N'Require RBI control evidence for production release',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,1,NULL,20),
(N'compliance',N'EvidenceReviewDays',N'Evidence Review Cycle',N'Maximum compliance evidence review interval days',N'Integer',N'90',NULL,1,365,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'monitoring',N'TpsWarning',N'TPS Warning',N'TPS warning threshold',N'Integer',N'5000',NULL,1,100000,N'Sensitive',N'HotReload',1,0,0,0,NULL,20),
(N'monitoring',N'DeclineRateCriticalPercent',N'Decline Rate Critical',N'Critical decline rate percent',N'Decimal',N'20',NULL,0,100,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'monitoring',N'QueueDepthCritical',N'Queue Depth Critical',N'Critical processing queue depth',N'Integer',N'3000',NULL,1,100000,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'monitoring',N'AvailabilitySlaPercent',N'Availability SLA',N'Required platform availability percentage',N'Decimal',N'99.95',NULL,90,100,N'Critical',N'HotReload',1,0,0,0,NULL,50),
(N'alerts',N'EmailEnabled',N'Email Alerts',N'Enable email operational alerts',N'Boolean',N'true',NULL,NULL,NULL,N'Operational',N'HotReload',0,0,0,0,NULL,20),
(N'alerts',N'SmsEnabled',N'SMS Alerts',N'Enable SMS critical alerts',N'Boolean',N'false',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'alerts',N'CriticalEscalationMinutes',N'Critical Escalation',N'Minutes before critical alert escalates',N'Integer',N'5',NULL,1,120,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'observability',N'OpenTelemetryEnabled',N'OpenTelemetry',N'Enable OpenTelemetry tracing/metrics',N'Boolean',N'true',NULL,NULL,NULL,N'Sensitive',N'HotReload',1,0,0,0,NULL,20),
(N'observability',N'TraceSamplingPercent',N'Trace Sampling %',N'OpenTelemetry trace sample percentage',N'Integer',N'10',NULL,0,100,N'Sensitive',N'HotReload',1,0,0,0,NULL,30),
(N'observability',N'SensitiveDataMasking',N'Sensitive Data Masking',N'Enforce sensitive value masking in logs',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,1,NULL,40),
(N'dr',N'Mode',N'DR Mode',N'Disaster recovery topology',N'Enum',N'ActivePassive',N'["ActivePassive","ActiveActive"]',NULL,NULL,N'Critical',N'ClusterRestart',1,0,0,0,NULL,30),
(N'dr',N'AutomaticFailoverEnabled',N'Automatic Failover',N'Enable automatic DR failover',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'dr',N'DrSiteCode',N'DR Site Code',N'Configured disaster recovery site identifier',N'String',N'DR1',NULL,NULL,NULL,N'Critical',N'ClusterRestart',1,0,0,0,NULL,50),
(N'retention',N'AuditDays',N'Audit Retention',N'Audit event retention days',N'Integer',N'2555',NULL,365,3650,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'retention',N'EjDays',N'EJ Retention',N'ATM electronic journal retention days',N'Integer',N'365',NULL,30,3650,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'retention',N'DisputeDays',N'Dispute Retention',N'Dispute case/evidence retention days',N'Integer',N'2555',NULL,365,3650,N'Critical',N'HotReload',1,0,0,0,NULL,40),
(N'retention',N'CertificationDays',N'Certification Retention',N'Certification evidence retention days',N'Integer',N'2555',NULL,365,3650,N'Critical',N'HotReload',1,0,0,0,NULL,50),
(N'feature-flags',N'ProductionPercentageRolloutAllowed',N'Production Percentage Rollout',N'Permit percentage feature rollout in PROD',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,10),
(N'feature-flags',N'RollbackOnHealthFailure',N'Rollback On Health Failure',N'Automatically rollback feature flag when health degrades',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,20),
(N'diagnostics',N'ProbeTimeoutSeconds',N'Probe Timeout',N'Maximum diagnostic dependency probe duration',N'Integer',N'5',NULL,1,60,N'Sensitive',N'HotReload',1,0,0,0,NULL,20),
(N'diagnostics',N'HsmProbeEnabled',N'HSM Probe',N'Enable privileged HSM connectivity probe',N'Boolean',N'true',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,30),
(N'diagnostics',N'NetworkProbeEnabled',N'Network Host Probe',N'Enable privileged scheme host connectivity probes',N'Boolean',N'false',NULL,NULL,NULL,N'Critical',N'HotReload',1,0,0,0,NULL,40);

MERGE dbo.ConfigurationDefinitions AS t
USING @defs s ON t.DomainCode=s.DomainCode AND t.[Key]=s.[Key]
WHEN MATCHED THEN UPDATE SET
 DisplayName=s.DisplayName, Description=s.Description, ValueType=s.ValueType, DefaultValue=s.DefaultValue, AllowedValuesJson=s.AllowedValuesJson,
 MinimumValue=s.MinimumValue, MaximumValue=s.MaximumValue, Sensitivity=s.Sensitivity, ReloadPolicy=s.ReloadPolicy, RequiresApproval=s.RequiresApproval,
 IsSecret=s.IsSecret, IsSensitive=s.IsSensitive, ProductionLocked=s.ProductionLocked, ValidationPattern=s.ValidationPattern, DisplayOrder=s.DisplayOrder, Enabled=1
WHEN NOT MATCHED THEN INSERT(Id,DomainCode,[Key],DisplayName,Description,ValueType,DefaultValue,AllowedValuesJson,MinimumValue,MaximumValue,Sensitivity,ReloadPolicy,RequiresApproval,IsSecret,IsSensitive,ProductionLocked,ValidationPattern,DisplayOrder,Enabled)
VALUES(NEWID(),s.DomainCode,s.[Key],s.DisplayName,s.Description,s.ValueType,s.DefaultValue,s.AllowedValuesJson,s.MinimumValue,s.MaximumValue,s.Sensitivity,s.ReloadPolicy,s.RequiresApproval,s.IsSecret,s.IsSensitive,s.ProductionLocked,s.ValidationPattern,s.DisplayOrder,1);

COMMIT TRANSACTION;
